global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['worker:8001']
        labels:
          service: worker
