name: CI

on:
  push:
    branches: [ master, develop/hazard, develop/safe ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.10, 3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Install dev dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: Run tests
        run: |
          python -m unittest discover -v
