name: CI

on:
  push:
    branches: [ main, migration, depreciated-models ]
  pull_request:
    branches: [ main ]

# Required for the workflow to push coverage-badge.json back to the repo
permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.10, 3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Install dev dependencies
        run: |
          pip install -r requirements-dev.txt || true
          pip install pytest pytest-cov
      - name: Run tests with coverage (offline)
        env:
          USE_REAL_TESTS: '0'
        run: |
          pytest --cov=agent --cov=tests --cov-report=xml --cov-report=term-missing -q
      - name: Secret scan
        run: |
          python scripts/secret_scan.py
      - name: Generate coverage badge JSON
        run: |
          python scripts/make_coverage_badge.py
      - name: Commit coverage badge (main branch only)
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add coverage-badge.json || true
          git commit -m "chore: update coverage badge" || echo "No changes"
          git push origin HEAD:${{ github.ref }}
